export const GET_USERS_LIST_START = "GET_USERS_LIST_START";
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_FAILED = "GET_USERS_LIST_FAILED";
export const GET_USERS_LIST_RESET = "GET_USERS_LIST_RESET ";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const GET_USER_DETAIL_BY_ADMIN_START = "GET_USER_DETAIL_BY_ADMIN_START";
export const GET_USER_DETAIL_BY_ADMIN_SUCCESS =
  "GET_USER_DETAIL_BY_ADMIN_SUCCESS";
export const GET_USER_DETAIL_BY_ADMIN_FAILED =
  "GET_USER_DETAIL_BY_ADMIN_FAILED";
export const GET_USER_DETAIL_BY_ADMIN_RESET = "GET_USER_DETAIL_BY_ADMIN_RESET";

export const UPDATE_USER_DETAIL_ADMIN_START = "UPDATE_USER_DETAIL_ADMIN_START";
export const UPDATE_USER_DETAIL_ADMIN_SUCCESS =
  "UPDATE_USER_DETAIL_ADMIN_SUCCESS";
export const UPDATE_USER_DETAIL_ADMIN_FAILED =
  "UPDATE_USER_DETAIL_ADMIN_FAILED";
export const RESET_UPDATE_USER_DETAIL_ADMIN_ERROR =
  "RESET_UPDATE_USER_DETAIL_ADMIN_ERROR";
export const RESET_UPDATE_USER_DETAIL_ADMIN_SUCCESS =
  "RESET_UPDATE_USER_DETAIL_ADMIN_SUCCESS";
