export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const TOGGLE_CART_ITEM_QTY = "OGGLE_CART_ITEM_QTY";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
