export const LOGIN_REQUEST_STARTED = "LOGIN_REQUEST_STARTED";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const NEW_LOGIN_ATTEMPT = "NEW_LOGIN_ATTEMPT";

export const REGISTER_REQUEST_STARTED = "REGISTER_REQUEST_STARTED";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAILED = "REGISTER_REQUEST_FAILED";
export const NEW_REGISTER_ATTEMPT = "NEW_REGISTER_ATTEMPT";

export const PROFILE_REQUEST_STARTED = "PROFILE_REQUEST_STARTED";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_FAILED = "PROFILE_REQUEST_FAILED";
export const PROFILE_REQUEST_RESET = "PROFILE_REQUEST_FAILED";

export const UPDATE_PROFILE_REQUEST_STARTED = "UPDATE_PROFILE_REQUEST_STARTED";
export const UPDATE_PROFILE_REQUEST_SUCCESS = "UPDATE_PROFILE_REQUEST_SUCCESS";
export const UPDATE_PROFILE_REQUEST_FAILED = "UPDATE_PROFILE_REQUEST_FAILED";

export const UPDATE_PASSWORD_REQUEST_STARTED =
  "UPDATE_PASSWORD_REQUEST_STARTED";
export const UPDATE_PASSWORD_REQUEST_SUCCESS =
  "UPDATE_PASSWORD_REQUEST_SUCCESS";
export const UPDATE_PASSWORD_REQUEST_FAILED = "UPDATE_PASSWORD_REQUEST_FAILED";
