export const LOGIN_REQUEST_STARTED = "LOGIN_REQUEST_STARTED";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const NEW_LOGIN_ATTEMPT = "NEW_LOGIN_ATTEMPT";
