export const PLACE_ORDER_START = "PLACE_ORDER_START";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";
export const GET_MY_ORDERS_START = "GET_MY_ORDERS_START";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAILED = "GET_MY_ORDERS_FAILED";
