export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const CLEAN_PRODUCT_LIST = "CLEAN_PRODUCT_LIST";

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START ";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS ";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED ";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET ";

export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START ";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS ";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED ";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START ";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS ";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED ";
