export const GET_SHIPPING_ADDRESS_START = "GET_SHIPPING_ADDRESS_START";
export const GET_SHIPPING_ADDRESS_SUCCESS = "GET_SHIPPING_ADDRESS_SUCCESS";
export const GET_SHIPPING_ADDRESS_FAILED = "GET_SHIPPING_ADDRESS_FAILED";

export const CREATE_SHIPPING_ADDRESS_START = "CREATE_SHIPPING_ADDRESS_START";
export const CREATE_SHIPPING_ADDRESS_SUCCESS =
  "CREATE_SHIPPING_ADDRESS_SUCCESS";
export const CREATE_SHIPPING_ADDRESS_FAILED = "CREATE_SHIPPING_ADDRESS_FAILED";

export const UPDATE_SHIPPING_ADDRESS_STARTED =
  "UPDATE_SHIPPING_ADDRESS_STARTED";
export const UPDATE_SHIPPING_ADDRESS_SUCCESS =
  "UPDATE_SHIPPING_ADDRESS_SUCCESS";
export const UPDATE_SHIPPING_ADDRESS_FAILED = "UPDATE_SHIPPING_ADDRESS_FAILED";
export const UPDATE_SHIPPING_POST_SUCCESS = "UPDATE_SHIPPING_POST_SUCCESS";
