export const SEND_ACTIVATION_TOKEN_STARTED = "SEND_ACTIVATION_TOKEN_STARTED";
export const SEND_ACTIVATION_TOKEN_SUCCESS = "SEND_ACTIVATION_TOKEN_SUCCESS";
export const SEND_ACTIVATION_TOKEN_FAILED = "SEND_ACTIVATION_TOKEN_FAILED";
