export const SEND_ACTIVATION_TOKEN_STARTED = "SEND_ACTIVATION_TOKEN_STARTED";
export const SEND_ACTIVATION_TOKEN_SUCCESS = "SEND_ACTIVATION_TOKEN_SUCCESS";
export const SEND_ACTIVATION_TOKEN_FAILED = "SEND_ACTIVATION_TOKEN_FAILED";

export const PROFILE_ACTIVATION_STARTED = "PROFILE_ACTIVATION_STARTED";
export const PROFILE_ACTIVATION_SUCCESS = "PROFILE_ACTIVATION_SUCCESS";
export const PROFILE_ACTIVATION_FAILED = "PROFILE_ACTIVATION_FAILED";
