export const SEND_ACTIVATION_TOKEN_STARTED = "SEND_ACTIVATION_TOKEN_STARTED";
export const SEND_ACTIVATION_TOKEN_SUCCESS = "SEND_ACTIVATION_TOKEN_SUCCESS";
export const SEND_ACTIVATION_TOKEN_FAILED = "SEND_ACTIVATION_TOKEN_FAILED";

export const PROFILE_ACTIVATION_STARTED = "PROFILE_ACTIVATION_STARTED";
export const PROFILE_ACTIVATION_SUCCESS = "PROFILE_ACTIVATION_SUCCESS";
export const PROFILE_ACTIVATION_FAILED = "PROFILE_ACTIVATION_FAILED";

export const SEND_RESET_PASSWORD_TOKEN_STARTED =
  "SEND_RESET_PASSWORD_TOKEN_STARTED";
export const SEND_RESET_PASSWORD_TOKEN_SUCCESS =
  "SEND_RESET_PASSWORD_TOKEN_SUCCESS";
export const SEND_RESET_PASSWORD_TOKEN_FAILED =
  "SEND_RESET_PASSWORD_TOKEN_FAILED";
export const RESET_SEND_PASSWORD_TOKEN = "RESET_SEND_PASSWORD_TOKEN";

export const PASSWORD_RESET_STARTED = "PASSWORD_RESET_STARTED";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";
export const RESET_PASSWORD_STATE = "RESET_PASSWORD_STATE";
